version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Tokyo"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
