version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "Asia/Tokyo"
    groups:
      dependencies:
        dependency-type: "production"
        update-types:
          - "patch"
      devDependencies:
        dependency-type: "development"
        update-types:
          - "patch"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
